name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore https://github.com/suleman26/dutchretreat/blob/master/Dutch%20retreat/Dutch%20retreat/dutch%20retreat.csproj
    - name: Build
      run: dotnet build https://github.com/suleman26/dutchretreat/blob/master/Dutch%20retreat/Dutch%20retreat/dutch%20retreat.csproj --no-restore
    - name: Test
      run: dotnet test https://github.com/suleman26/dutchretreat/blob/master/Dutch%20retreat/Dutch%20retreat/dutch%20retreat.csproj --no-build --verbosity normal
